config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'order_shops/index'
  get 'order_shops/show'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  get 'customers/new'
  get '/search', to: 'pages#search_product_by_name'
  get 'categories/index'
  get 'categories/new'
  get 'sessions/new'
  get 'shops/new'
  get  '/about',          to: 'static_pages#about'
  get  '/help',           to: 'static_pages#help'
  get  '/contact',        to: 'static_pages#contact'
  get  '/signup_shop',    to: 'shops#new'
  post '/signup_shop',    to: 'shops#create'
  get  '/login_shop',     to: 'sessions#new_shop'
  post '/login_shop',     to: 'sessions#create_shop'
  delete '/logout_shop',  to: 'sessions#destroy_shop'
  get '/signup',          to: 'customers#new'
  get '/login',           to: 'sessions#new_customer'
  post '/login',          to: 'sessions#create_customer'
  delete '/logout',       to: 'sessions#destroy_customer'

  get '/order_shops',     to: 'order_shops#index'
  get '/order_shops/:id', to: 'order_shops#show', as: 'order_shop'

  get '/carts/:id',       to: 'carts#show', as: 'cart'
  delete '/carts/:id',    to: 'carts#destroy'

  post '/line_items/:id/add',    to: 'line_items#add_quantity',    as: 'line_item_add'
  post '/line_items/:id/reduce', to: 'line_items#reduce_quantity', as: 'line_item_reduce'
  post '/line_items',            to: 'line_items#create'
  get '/line_items/:id',         to: 'line_items#show',            as: 'line_item'
  delete '/line_items/:id',      to: 'line_items#destroy'

  resources :shops
  resources :products
  resources :categories
  resources :customers
  resources :orders
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # Return total_price of cart
  def sub_total
    total_price_of_cart = 0
    line_items.each do |line_item|
      total_price_of_cart += line_item.total_price
    end
    total_price_of_cart
  end

  # Return total quantity of cart
  def total_quantity
    total_quantity = 0
    line_items.each do |line_item|
      total_quantity += line_item.quantity
    end
    total_quantity
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<% provide(:title, "Your Cart") %>

<h1>Your Cart</h1>
<% if @current_cart.total_quantity > 0 %>
  <table id="cart" class="table table-hover table-condensed">
    <thead>
    <tr>
      <th style="width:50%">Product</th>
      <th style="width:10%">Price</th>
      <th style="width:8%">Quantity</th>
      <th style="width:22%" class="text-center">Subtotal</th>
      <th style="width:10%"></th>
    </tr>
    </thead>
    <tbody>
    <% @cart.line_items.each do |line_item| %>
      <tr>
        <td data-th="Product">
          <div class="row">
            <div class="col-sm-2 hidden-xs">
              <img src="<%= line_item.product.picture %>" alt="<%= line_item.product.name %>" style="width: 90px; height: 100px">
            </div>
            <div class="col-sm-10">
              <h4 class="nomargin"><%= line_item.product.name %></h4>
              <p><%= line_item.product.description %></p>
            </div>
          </div>
        </td>
        <td data-th="Price"><%= number_to_currency(line_item.product.price, unit: "", delimiter: ".", precision: 0) %></td>
        <td data-th="Quantity">
          <input type="number" class="form-control text-center" value="<%= line_item.quantity %>">
        </td>
        <td data-th="Subtotal" class="text-center">
          <%= number_to_currency(line_item.total_price, unit: "", delimiter: ".", precision: 0) %>
        </td>
        <td class="actions" data-th="">
          <%= link_to "Remove item", line_item_path(line_item), method: :delete %>
          <%= link_to "Add one", line_item_add_path(:id => line_item), method: :post %>
          <%= link_to "Reduce one", line_item_reduce_path(:id => line_item), method: :post %>
        </td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td><%= link_to "Continue Shopping", root_path, class: "btn btn-md btn-primary" %></td>
      <td colspan="2" class="hidden-xs"></td>
      <td class="hidden-xs text-center" style="">
        <strong><%= number_to_currency(@cart.sub_total, unit: "", delimiter: ".", precision: 0) %> VND</strong>
      </td>
      <td><%= link_to "Check Out", new_order_path, class: "btn btn-md btn-success" %></td>
    </tr>
    </tfoot>
  </table>
<% else %>
  <h3>Your cart is empty!</h3>
  <div>
    Why not add something?
    <%= link_to "Continue Shopping", root_path, class: "btn btn-md btn-primary" %>
  </div>
<% end %>