config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'order_shops/index'
  get 'order_shops/show'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  get 'customers/new'
  get '/search', to: 'pages#search_product_by_name'
  get 'categories/index'
  get 'categories/new'
  get 'sessions/new'
  get 'shops/new'
  get  '/about',          to: 'static_pages#about'
  get  '/help',           to: 'static_pages#help'
  get  '/contact',        to: 'static_pages#contact'
  get  '/signup_shop',    to: 'shops#new'
  post '/signup_shop',    to: 'shops#create'
  get  '/login_shop',     to: 'sessions#new_shop'
  post '/login_shop',     to: 'sessions#create_shop'
  delete '/logout_shop',  to: 'sessions#destroy_shop'
  get '/signup',          to: 'customers#new'
  get '/login',           to: 'sessions#new_customer'
  post '/login',          to: 'sessions#create_customer'
  delete '/logout',       to: 'sessions#destroy_customer'

  get '/order_shops',     to: 'order_shops#index'
  get '/order_shops/:id', to: 'order_shops#show', as: 'order_shop'

  get '/carts/:id',       to: 'carts#show', as: 'cart'
  delete '/carts/:id',    to: 'carts#destroy'

  post '/line_items/:id/add',    to: 'line_items#add_quantity',    as: 'line_item_add'
  post '/line_items/:id/reduce', to: 'line_items#reduce_quantity', as: 'line_item_reduce'
  post '/line_items',            to: 'line_items#create'
  get '/line_items/:id',         to: 'line_items#show',            as: 'line_item'
  delete '/line_items/:id',      to: 'line_items#destroy'

  resources :shops
  resources :products
  resources :categories
  resources :customers
  resources :orders
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :shop
  has_many :products_categories
  has_many :products, through: :products_categories

  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true, length: { maximum: 150 }
  validates :description, presence: true, length: { maximum: 255 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_shop, only: %i[index new edit create update destroy]
  before_action :correct_shop,   only: %i[edit update destroy]

  def index
    @categories = current_shop.categories.paginate(page: params[:page])
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products.paginate(page: params[:page], per_page: 8)
  end

  def new
    @category = current_shop.categories.build if logged_in_shop?
  end

  def create
    @category = current_shop.categories.build(category_params)
    if @category.save
      flash[:success] = 'Category created!'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = current_shop.categories.find(params[:id]) if logged_in_shop?
  end

  def update
    @category = current_shop.categories.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = 'Category updated!'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = current_shop.categories.find(params[:id])
    @category.destroy
    flash[:success] = 'Category deleted!'
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def correct_shop
    @category = current_shop.categories.find_by(id: params[:id])
    redirect_to root_url if @category.nil?
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<% provide(:title, "Edit category") %>
<h1>Edit category</h1>

<%= form_for(@category) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>

    <%= f.submit "Save changes", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<% provide(:title, "Categories") %>

<div style="text-align: center;"><h1>List categories</h1></div>
<%= link_to "New category", new_category_path, class: "btn btn-primary" %>

<table class="table table-striped table-bordered" style="margin-top: 10px">
  <thead>
  <tr>
    <th scope="col">ID</th>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |c| %>
    <tr>
      <th scope="row"><%= c.id %></th>
      <td><%= c.name %></td>
      <td><%= c.description %></td>
      <td><%= link_to "Delete", category_path(c), method: :delete, data: { confirm: "Are you sure?" } %>
        | <%= link_to "Edit", edit_category_path(c) %> | <%= link_to "View", category_path(c) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<div style="text-align: center;"><%= will_paginate @categories %></div>

app/views/categories/new.html.erb
<% provide(:title, "Create category") %>
<h1>Create category</h1>

<%= form_for(@category) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>

    <%= f.submit "Create category", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>

<div style="text-align: center;"><h1><%= @category.name %></h1></div>

<div class="row product-list">
  <% @products.each do |p| %>
    <div class="col-md-3 product">
      <div class="product-card">
        <%= link_to image_tag("#{p.picture}"), product_path(p.id), alt: p.name %>
        <h2><%= p.name %></h2>
        <p class="price"><%= number_to_currency(p.price, unit: "", delimiter: ".", precision: 0) %> ₫</p>
        <p class="desc"><%= p.description %></p>
        <%= button_to 'Add to cart', line_items_path(:product_id => p.id), class: 'add-to-cart-button'%>
      </div>
    </div>
  <% end %>
</div>

<div style="text-align: center;"><%= will_paginate @products %></div>

<script>
    $(document).ready(function(){
        $('.review-rating').raty({
            readOnly: true,
            score: function() {
                return $(this).attr('data-score');
            },
            path: '/assets/',
        });
    });

    $(document).ready(function(){
        $('#rating-form').raty({
            readOnly: true,
            path: '/assets/',
        });
    });
</script>