config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'order_shops/index'
  get 'order_shops/show'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  get 'customers/new'
  get '/search', to: 'pages#search_product_by_name'
  get 'categories/index'
  get 'categories/new'
  get 'sessions/new'
  get 'shops/new'
  get  '/about',          to: 'static_pages#about'
  get  '/help',           to: 'static_pages#help'
  get  '/contact',        to: 'static_pages#contact'
  get  '/signup_shop',    to: 'shops#new'
  post '/signup_shop',    to: 'shops#create'
  get  '/login_shop',     to: 'sessions#new_shop'
  post '/login_shop',     to: 'sessions#create_shop'
  delete '/logout_shop',  to: 'sessions#destroy_shop'
  get '/signup',          to: 'customers#new'
  get '/login',           to: 'sessions#new_customer'
  post '/login',          to: 'sessions#create_customer'
  delete '/logout',       to: 'sessions#destroy_customer'

  get '/order_shops',     to: 'order_shops#index'
  get '/order_shops/:id', to: 'order_shops#show', as: 'order_shop'

  get '/carts/:id',       to: 'carts#show', as: 'cart'
  delete '/carts/:id',    to: 'carts#destroy'

  post '/line_items/:id/add',    to: 'line_items#add_quantity',    as: 'line_item_add'
  post '/line_items/:id/reduce', to: 'line_items#reduce_quantity', as: 'line_item_reduce'
  post '/line_items',            to: 'line_items#create'
  get '/line_items/:id',         to: 'line_items#show',            as: 'line_item'
  delete '/line_items/:id',      to: 'line_items#destroy'

  resources :shops
  resources :products
  resources :categories
  resources :customers
  resources :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shop
  has_many :products_categories
  has_many :categories, through: :products_categories
  has_many :line_items, dependent: :destroy
  has_one :product_rating, inverse_of: :product, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :product_rating

  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :shop_id, presence: true
  validates :name, presence: true, length: { maximum: 150 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :price, presence: true
  validates :total, presence: true
  validates :picture, presence: true
  validate :picture_size

  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, 'should be less than 5MB')
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_shop, only: %i[index new edit create update destroy]
  before_action :correct_shop,   only: %i[edit update destroy]

  def index
    @products = current_shop.products.paginate(page: params[:page], per_page: 8)
  end

  def show
    @product = Product.find(params[:id])
    if logged_in_shop?
      @correct_product = current_shop.products.find_by(id: @product.id)
    end
  end

  def new
    if logged_in_shop?
      @product = current_shop.products.build
      @product_rating = @product.build_product_rating
    end
  end

  def create
    @product = current_shop.products.build(product_params)
    if @product.save
      flash[:success] = "Product created!"
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    if logged_in_shop?
      @product = current_shop.products.find(params[:id])
    end
  end

  def update
    @product = current_shop.products.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] = "Product updated."
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "product deleted"
    redirect_to products_path
  end

  private

  def correct_shop
    @product = current_shop.products.find_by(id: params[:id])
    redirect_to root_url if @product.nil?
  end

  def product_params
    params.require(:product).permit(:name, :description, :price,
                                    :total, :picture, :category_ids,
                                    product_rating_attributes: %i[id product_id rating],)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<% provide(:title, "Edit product") %>
<h1>Edit product</h1>

<%= form_for(@product) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :name, "Product name" %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>

    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control" %>

    <%= f.label :total, "quantity" %>
    <%= f.text_field :total, class: "form-control" %>

    <% if @product.product_rating.present? %>
      <div class="review-rating" data-score = "<%= @product.product_rating.rating %>">
        <label>Rating</label>
      </div>
    <% else %>
      <div id="rating-form">
        <label>Rating</label>
      </div>
    <% end %>

    <span><img src="<%= @product.picture %>" style="width: 212px; height: 200px" alt="product"></span>

    <span class="picture">
      <%= f.file_field :picture %>
    </span>

    <%= f.submit "Save changes", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
    $(document).ready(function(){
        $('.review-rating').raty({
            score: function() {
                return $(this).attr('data-score');
            },
            half: true,
            cancel: true,
            cancelPlace: 'right',
            path: '/assets/',
            starHalf: 'big_star_half',
            starOn: 'big_star_on',
            starOff: 'big_star_off',
            scoreName: 'product[product_rating_attributes][rating]'
        });
    });

    $(document).ready(function(){
        $('#rating-form').raty({
            half: true,
            cancel: true,
            cancelPlace: 'right',
            path: '/assets/',
            scoreName: 'product[product_rating_attributes][rating]'
        });
    });
</script>

app/views/products/index.html.erb
<% provide(:title, "Products") %>

<div style="text-align: center;"><h1>List products</h1></div>
<%= link_to "New product", new_product_path, class: "btn btn-primary" %>

<div class="row product-list">
  <% @products.each do |p| %>
    <div class="col-md-3 product">
      <div class="product-card">
        <%= link_to image_tag("#{p.picture}"), product_path(p.id), alt: p.name %>
        <h2><%= p.name %></h2>
        <p class="price"><%= number_to_currency(p.price, unit: "", delimiter: ".", precision: 0) %> ₫</p>
        <p class="desc"><%= p.description %></p>
        <%= button_to 'Add to cart', line_items_path(:product_id => p.id), class: 'add-to-cart-button'%>
      </div>
    </div>
  <% end %>
</div>

<div style="text-align: center;"><%= will_paginate @products %></div>

<script>
    $(document).ready(function(){
        $('.review-rating').raty({
            readOnly: true,
            score: function() {
                return $(this).attr('data-score');
            },
            path: '/assets/',
        });
    });

    $(document).ready(function(){
        $('#rating-form').raty({
            readOnly: true,
            path: '/assets/',
        });
    });
</script>

app/views/products/new.html.erb
<% provide(:title, "Create product") %>
<h1>Create product</h1>

<%= form_for(@product) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :name, "Product name" %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :category_ids, "Select category" %>
    <%= f.collection_select :category_ids, current_shop.categories, :id, :name %>

    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>

    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control" %>

    <%= f.label :total, "quantity" %>
    <%= f.text_field :total, class: "form-control" %>

    <%#= f.fields_for :product_rating do |product_rating| %>
      <%#= product_rating.label :rating %>
      <%#= product_rating.number_field :rating, class: "form-control" %>
    <%# end %>
    <div id="rating-form">
      <label>Rating</label>
    </div>

    <span class="picture">
      <%= f.file_field :picture %>
    </span>

    <%= f.submit "Create product", class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  $(document).ready(function(){
      $('#rating-form').raty({
          half: true,
          cancel: true,
          cancelPlace: 'right',
          path: '/assets/',
          scoreName: 'product[product_rating_attributes][rating]'
      });
  });
</script>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>

<div><h1>Product detail</h1></div>
<div class="card">
  <div class="row">
    <aside class="col-sm-5 border-right">
      <article class="gallery-wrap">
        <div class="img-big-wrap">
          <div> <a href="#"><img src="<%= @product.picture %>" alt="<%= @product.name %>"></a></div>
        </div> <!-- slider-product.// -->
      </article> <!-- gallery-wrap .end// -->
    </aside>
    <aside class="col-sm-7">
      <article class="card-body p-5">
        <h3 class="title mb-3"><%= @product.name %></h3>
        <% if @product.product_rating.present? %>
          <div class="review-rating" data-score = "<%= @product.product_rating.rating %>">
            <label>Rating</label>
          </div>
        <% else %>
          <div id="rating-form">
            <label>Rating</label>
          </div>
        <% end %>
        <p class="price-detail-wrap">
          <span class="price h3 text-warning">
            <span class="currency"></span><span class="num">
              <%= number_to_currency(@product.price, unit: "", delimiter: ".", precision: 0) %> VND
            </span>
          </span>
        </p> <!-- price-detail-wrap .// -->
        <dl class="item-property">
          <dt>Description</dt>
          <dd><p><%= @product.description %></p></dd>
        </dl>
        <dl class="param param-feature">
          <dt>Delivery</dt>
          <dd>Viet Nam, Russia, USA, and Europe</dd>
        </dl>  <!-- item-property-hor .// -->
        <hr>
        <div class="row">
          <div class="col-sm-5">
            <dl class="param param-inline">
              <dt>Quantity: </dt>
              <dd>
                <select class="form-control form-control-sm" style="width:70px;">
                  <option> 1 </option>
                  <option> 2 </option>
                  <option> 3 </option>
                </select>
              </dd>
            </dl>  <!-- item-property .// -->
          </div> <!-- col.// -->
        </div> <!-- row.// -->
        <hr>
        <% if @correct_product %>
          <%= link_to "delete", @product, method: :delete, data: { confirm: "Are you sure?" },
                      class: "btn btn-lg btn-danger text-uppercase" %>
          <%= link_to "edit", edit_product_path, class: "btn btn-lg btn-success text-uppercase" %>
        <% end %>
        <% unless logged_in_shop? %>
          <%= button_to "ADD TO CART", line_items_path(:product_id => @product.id), class: "btn btn-lg btn-primary" %>
        <% end %>
      </article> <!-- card-body.// -->
    </aside> <!-- col.// -->
  </div> <!-- row.// -->
</div> <!-- card.// -->

<script>
    $(document).ready(function(){
        $('.review-rating').raty({
            readOnly: true,
            score: function() {
                return $(this).attr('data-score');
            },
            path: '/assets/',
        });
    });

    $(document).ready(function(){
        $('#rating-form').raty({
            readOnly: true,
            path: '/assets/',
        });
    });
</script>