config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'order_shops/index'
  get 'order_shops/show'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  get 'customers/new'
  get '/search', to: 'pages#search_product_by_name'
  get 'categories/index'
  get 'categories/new'
  get 'sessions/new'
  get 'shops/new'
  get  '/about',          to: 'static_pages#about'
  get  '/help',           to: 'static_pages#help'
  get  '/contact',        to: 'static_pages#contact'
  get  '/signup_shop',    to: 'shops#new'
  post '/signup_shop',    to: 'shops#create'
  get  '/login_shop',     to: 'sessions#new_shop'
  post '/login_shop',     to: 'sessions#create_shop'
  delete '/logout_shop',  to: 'sessions#destroy_shop'
  get '/signup',          to: 'customers#new'
  get '/login',           to: 'sessions#new_customer'
  post '/login',          to: 'sessions#create_customer'
  delete '/logout',       to: 'sessions#destroy_customer'

  get '/order_shops',     to: 'order_shops#index'
  get '/order_shops/:id', to: 'order_shops#show', as: 'order_shop'

  get '/carts/:id',       to: 'carts#show', as: 'cart'
  delete '/carts/:id',    to: 'carts#destroy'

  post '/line_items/:id/add',    to: 'line_items#add_quantity',    as: 'line_item_add'
  post '/line_items/:id/reduce', to: 'line_items#reduce_quantity', as: 'line_item_reduce'
  post '/line_items',            to: 'line_items#create'
  get '/line_items/:id',         to: 'line_items#show',            as: 'line_item'
  delete '/line_items/:id',      to: 'line_items#destroy'

  resources :shops
  resources :products
  resources :categories
  resources :customers
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # Return total_price of cart
  def sub_total
    total_price_of_cart = 0
    line_items.each do |line_item|
      total_price_of_cart += line_item.total_price
    end
    total_price_of_cart
  end

  # Return total quantity of cart
  def total_quantity
    total_quantity = 0
    line_items.each do |line_item|
      total_quantity += line_item.quantity
    end
    total_quantity
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :shop
  has_many :products_categories
  has_many :products, through: :products_categories

  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true, length: { maximum: 150 }
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :phone, presence: true, length: { maximum: 20, minimum: 10 }
  validates :address, presence: true, length: { maximum: 255 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional: true

  # Return total_price of each line_item
  def total_price
    quantity * product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord

  before_save { self.email = email.downcase }
  has_many :line_items, dependent: :destroy
  belongs_to :customer

  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  validates :phone, presence: true, length: { maximum: 20, minimum: 10 }
  validates :address, presence: true, length: { maximum: 255 }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shop
  has_many :products_categories
  has_many :categories, through: :products_categories
  has_many :line_items, dependent: :destroy
  has_one :product_rating, inverse_of: :product, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :product_rating

  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :shop_id, presence: true
  validates :name, presence: true, length: { maximum: 150 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :price, presence: true
  validates :total, presence: true
  validates :picture, presence: true
  validate :picture_size

  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, 'should be less than 5MB')
    end
  end
end

app/models/product_rating.rb
class ProductRating < ApplicationRecord
  belongs_to :product, inverse_of: :product_rating
  validates_presence_of :product
end

app/models/products_category.rb
class ProductsCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
  validates :product_id, uniqueness: { scope: :category_id }
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :categories, dependent: :destroy

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :phone, presence: true, length: { maximum: 20 }
  validates :address, presence: true, length: { maximum: 255 }
  validates :description, length: { maximum: 255 }
  validates :tax_code, presence: true, length: { maximum: 20 }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Defines a proto-feed
  def feed
    Product.where('shop_id = ?', id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = 'Hopee Shopping Cart'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given shop.
  def log_in(shop)
    session[:shop_id] = shop.id
  end

  # Returns true if the given shop is the current shop.
  def current_shop?(shop)
    shop == current_shop
  end

  # Returns the current logged-in shop (if any).
  def current_shop
    @current_shop ||= Shop.find_by(id: session[:shop_id]) if session[:shop_id]
  end

  # Check logged-in shop, returns boolean
  def logged_in_shop?
    !current_shop.nil?
  end

  # Logs out the current shop
  def log_out
    session.delete(:shop_id)
    @current_shop = nil
  end

  # Logs in the given customer.
  def log_in_customer(customer)
    session[:customer_id] = customer.id
  end

  # Returns the current logged-in customer (if any).
  def current_customer
    if session[:customer_id]
      @current_customer ||= Customer.find_by(id: session[:customer_id])
    end
  end

  # Returns true if the given customer is the current customer.
  def current_customer?(customer)
    customer == current_customer
  end

  def logged_in_customer?
    !current_customer.nil?
  end

  def log_out_customer
    session.delete(:customer_id)
    @current_customer = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/shops_helper.rb
module ShopsHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(people, size: 130)
    gravatar_id  = Digest::MD5.hexdigest(people.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: people.name, class: 'gravatar')
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright Hopee Shopping Cart &copy;2020.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<% if logged_in_shop? %>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Hopee Shopping Cart", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= form_tag(search_path, :method => "get",
                         class: 'navbar-form navbar-left') do %>
              <div class="input-group">
                <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
                <div class="input-group-btn">
                  <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>
                </div>
              </div>
            <% end %>
          </li>

          <li><%= link_to "Home",   root_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Products <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li style="padding-left: 20px"><h4>All categories</h4></li>
              <% categories = current_shop.categories %>
              <% categories.each do |c| %>
                <li class="divider"></li>
                <li><%= link_to c.name, category_path(c.id) if c.id %></li>
              <% end %>
            </ul>
          </li>

          <% if logged_in_shop? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Shop account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_shop %></li>
                <li><%= link_to "Products", products_path %></li>
                <li><%= link_to "Categories", categories_path %></li>
                <li><%= link_to "Ordered list of customer", order_shops_path %></li>
                <li><%= link_to "Settings", edit_shop_path(current_shop) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out shop", logout_shop_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login shop", login_shop_path %></li>
          <% end %>

          <li><%= link_to "Help",   help_path %></li>
        </ul>
      </nav>
    </div>
  </header>

<% elsif logged_in_customer? %>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Hopee Shopping Cart", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= form_tag(search_path, :method => "get",
                         class: 'navbar-form navbar-left') do %>
              <div class="input-group">
                <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
                <div class="input-group-btn">
                  <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>
                </div>
              </div>
            <% end %>
          </li>

          <li><%= link_to "Home",   root_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Products <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li style="padding-left: 20px"><h4>All categories</h4></li>
              <% categories = Category.all %>
              <% categories.each do |c| %>
                <li class="divider"></li>
                <li><%= link_to c.name, category_path(c.id) if c.id %></li>
              <% end %>
            </ul>
          </li>

          <% if logged_in_customer? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_customer %></li>
                <li><%= link_to "Ordered list", orders_path %></li>
                <li><%= link_to "Settings", edit_customer_path(current_customer) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>

          <li><%= link_to "Cart", cart_path(@current_cart) %>
            <% if !@current_cart.total_quantity.zero? %>
            <span class='badge badge-warning' style="position: absolute; top: 1px; left: 35px">
              <%= @current_cart.total_quantity %>
            </span>
            <% end %>
          </li>

          <li><%= link_to "Help",   help_path %></li>
        </ul>
      </nav>
    </div>
  </header>

<% else %>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Hopee Shopping Cart", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= form_tag(search_path, :method => "get",
                         class: 'navbar-form navbar-left') do %>
              <div class="input-group">
                <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
                <div class="input-group-btn">
                  <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>
                </div>
              </div>
            <% end %>
          </li>

          <li><%= link_to "Home",   root_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Products <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li style="padding-left: 20px"><h4>All categories</h4></li>
              <% categories = Category.all %>
              <% categories.each do |c| %>
                <li class="divider"></li>
                <li><%= link_to c.name, category_path(c.id) if c.id %></li>
              <% end %>
            </ul>
          </li>

          <% if logged_in_customer? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_customer %></li>
                <li><%= link_to "List order", orders_path %></li>
                <li><%= link_to "Settings", edit_customer_path(current_customer) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>

          <% if logged_in_shop? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Shop account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_shop %></li>
                <li><%= link_to "Products", products_path %></li>
                <li><%= link_to "Categories", categories_path %></li>
                <li><%= link_to "Settings", edit_shop_path(current_shop) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out shop", logout_shop_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login shop", login_shop_path %></li>
          <% end %>

          <li><%= link_to "Cart", cart_path(@current_cart) %>
            <% if !@current_cart.total_quantity.zero? %>
            <span class='badge badge-warning' style="position: absolute; top: 1px; left: 35px">
              <%= @current_cart.total_quantity %>
            </span>
            <% end %>
          </li>

          <li><%= link_to "Help",   help_path %></li>
        </ul>
      </nav>
    </div>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raty/2.9.0/jquery.raty.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>